### ISSUE TITLE
Show the geometric mean

### ISSUE THREAD

**Issue by LifeIsStrange** [quickwit-inc/search-benchmark-game#34]
It would be *really nice* to add a new row in the benchmarck results, showing the geometric mean of each library.
It make quick comparison easier (although since it's a much more coarse grained analysis it does not replace individual benchmarck queries comparisons) and more importantly, it make showing overall progress or regress after an update, much easier to detect and quantify.

*edit* OK I'm dumb there is already a row AVERAGE.
However do you use geometric mean instead of arithmetic mean?
I have the belief that geometric mean is better for comparison than arithmetic mean?
https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.cse.unsw.edu.au/~cs9242/18/papers/Fleming_Wallace_86.pdf&ved=2ahUKEwip_sTZuqD0AhUmRvEDHe7cD74QFnoECAQQBg&usg=AOvVaw2v4uabJpajKg5JmuJWXbvL

**Comment by fulmicoton** [comment]
I like arithmetic mean here as it translates directly into throughput figures.
