### ISSUE TITLE
What is meant by maxscore?

### ISSUE THREAD

**Issue by LifeIsStrange** [quickwit-inc/search-benchmark-game#35]
The readme says:
> Maxscore is not yet used in Top 10. It should give a nice boost once Lucene 8 is released.

I am a noob in search technologies but modern optimizations catch my curiosity so if anyone could expand about it that would be great!

Is maxscore used out of the box or require an explicit API (for lucene)? (if the former then it can be removed from the readme since the benchmark has been updated to Lucene 8 a long time ago)
Also it seems that in fact, Lucene 8 superseded maxscore with a successor optimization?
-> https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7148045/

**Comment by fulmicoton** [comment]
Sorry the readme was not up to date. Lucene's version was upgraded and Max score is used.
